spring.application.name=Genealogia

#. Conexão Segura e Forçada com o MySQL do Railway (Suporta Acentos e Fusos Horários)
spring.datasource.url=jdbc:${MYSQL_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# 1. Conexao Dinamica (Local vs Railway)
#spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/arvore}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=${MYSQLUSER:root}
#spring.datasource.password=${MYSQLPASSWORD:Gur1j0$e2026!}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate em modo UPDATE
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Gerenciamento pelo Flyway
spring.flyway.enabled=true
spring.flyway.baseline-version=true
spring.flyway.locations=classpath:db/migration
################################################
# 4. Porta Dinamica para Nuvem
server.port=${PORT:8080}
server.address=0.0.0.0

# 5. JWT Fixo em Producao
jwt.secret=879023****************************************************067e6a
jwt.expiration=86400000

# 6. Logs do Spring Security
logging.level.org.springframework.security=INFO
